-
  name: Install and Setup MySQL
  hosts: mysql
  tasks:
    - include_vars: mysql.vars.yml
    - name: Changing Hostname
      become: yes
      hostname:
        name: "{{ hostname }}"
    - name: add hostname to /etc/hosts
      become: yes
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost {{ hostname }}'
        state: present
    - name: Fix resolv.conf
      become: yes
      template: 
        src: "./templates/resolv.cnf" 
        dest: "/etc/resolv.conf"
        mode: "0600"
    - name: clean script
      become: yes
      template: 
        src: "./templates/clean.sh" 
        dest: "/root/clean.sh"
        mode: "0755"
    - name: Execute clean
      become: yes
      command: /root/clean.sh
    - name: Install Mysql
      become: yes
      yum:
        name: mariadb-server
        state: present
    - name: Start Mysql
      become: yes
      service:
        name: mariadb
        state: started
        enabled: true
    - name: Install the Python MySQL Support Libraries
      become: yes
      yum: 
        name: MySQL-python 
        state: present
    - name: update mysql root password for all root accounts
      mysql_user:
        name: "{{ mysql_user }}"
        host: "{{ item }}"
        password: "{{ mysql_password }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ mysql_subnet }}"
        - 127.0.0.1
        - ::1
        - localhost
    - name: Copy the root credentials as .my.cnf file
      template: 
        src: "./templates/my.cnf" 
        dest: "~/.my.cnf"
        mode: "0600"
    - name: Create a new databases for 'icinga'
      mysql_db:
        name: "{{ item }}"
        state: present
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: 127.0.0.1
      with_items:
        - "icinga"
        - "icingaweb2"
    - name: create icinga db user
      mysql_user:
        name: "{{ item }}"
        host: "{{ mysql_subnet }}"
        password: "{{ icinga_password }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        check_implicit_admin: yes
        priv: "{{ item }}.*:ALL,GRANT"
      with_items:
        - "icinga"
        - "icingaweb2"
    - name: mysql.sql
      become: yes
      template:
        src: templates/icingaweb/base/mysql.sql
        dest: /tmp/mysql.sql
        owner: terraform
        group: terraform
        mode: 0755
    - name: Import icinga2 schema
      mysql_db:
        state: import
        name: icinga
        target: /tmp/mysql.sql
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
    - name: icingaweb2_base.sql
      become: yes
      template:
        src: templates/icingaweb/base/icingaweb2_base.sql
        dest: /tmp/icingaweb2_base.sql
        owner: terraform
        group: terraform
        mode: 0755
    - name: Import icingaweb2 schema
      mysql_db:
        state: import
        name: icingaweb2
        target: /tmp/icingaweb2_base.sql
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"